### ISSUE TITLE
Como observador puedo asignar un curul a un diputado.

### ISSUE THREAD

**Issue by walreyes** [hackerschoolmty/congreso-abierto#33]

**Comment by juliazo** [comment]
Cuando se asigne el curul al mismo tiempo sera creado el asiento de esta manera el observador podra controlar las filas y columnas que conforman el congreso pensando que diferentes congresos estatales asi como el federal tendran un diagrama diferente en cuestion a como se acomodan los asientos

**Comment by juliazo** [comment]
hice un legislature_representatives donde se asigna al diputado la legislatura, partido, curul y distrito fue como se me ocurrio
